/*
 * @Author: NEFU AB-IN
 * @Date: 2022-03-25 20:05:38
 * @FilePath: \Acwing\TMP.CPP
 * @LastEditTime: 2022-09-05 16:20:15
 */
#include <bits/stdc++.h>
using namespace std;
#define int long long
#define SZ(X) ((int)(X).size())
#define IOS                                                                                                            \
    ios::sync_with_stdio(false);                                                                                       \
    cin.tie(0);                                                                                                        \
    cout.tie(0);
#define DEBUG(X) cout << #X << ": " << X << endl;
typedef pair<int, int> PII;

const int INF = INT_MAX;
const int N = 1e6 + 10;

signed main()
{
    IOS;
    double you = 91.04 * 0.85 + (11 + 0.4) * 0.15;
    double me = 79.002;
    DEBUG(me);
    DEBUG(you);
    return 0;
}