/*
 * @Author: NEFU AB-IN
 * @Date: 2022-04-19 17:55:57
 * @FilePath: \ACM\GPLT\tempCodeRunnerFile.CPP
 * @LastEditTime: 2022-04-22 19:40:25
 */
#include <bits/stdc++.h>
using namespace std;
#define int long long
#define MP make_pair
#define SZ(X) ((int)(X).size())
#define IOS                                                                                                            \
    ios::sync_with_stdio(false);                                                                                       \
    cin.tie(0);                                                                                                        \
    cout.tie(0);
#define DEBUG(X) cout << #X << ": " << X << endl;
typedef pair<int, int> PII;
const int INF = 0x3f3f3f3f;

signed main()
{
    IOS;
    vector<int> v(4, 1);
    for (auto i : v)
        cout << i;
    return 0;
}